/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SysRouteRouteImport } from './routes/sys/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SysUserRouteImport } from './routes/sys/user'
import { Route as SysRoleRouteImport } from './routes/sys/role'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SysRouteRoute = SysRouteRouteImport.update({
  id: '/sys',
  path: '/sys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SysUserRoute = SysUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => SysRouteRoute,
} as any)
const SysRoleRoute = SysRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => SysRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sys': typeof SysRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sys/role': typeof SysRoleRoute
  '/sys/user': typeof SysUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sys': typeof SysRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sys/role': typeof SysRoleRoute
  '/sys/user': typeof SysUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sys': typeof SysRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sys/role': typeof SysRoleRoute
  '/sys/user': typeof SysUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sys' | '/about' | '/sys/role' | '/sys/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sys' | '/about' | '/sys/role' | '/sys/user'
  id: '__root__' | '/' | '/sys' | '/about' | '/sys/role' | '/sys/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SysRouteRoute: typeof SysRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys': {
      id: '/sys'
      path: '/sys'
      fullPath: '/sys'
      preLoaderRoute: typeof SysRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys/user': {
      id: '/sys/user'
      path: '/user'
      fullPath: '/sys/user'
      preLoaderRoute: typeof SysUserRouteImport
      parentRoute: typeof SysRouteRoute
    }
    '/sys/role': {
      id: '/sys/role'
      path: '/role'
      fullPath: '/sys/role'
      preLoaderRoute: typeof SysRoleRouteImport
      parentRoute: typeof SysRouteRoute
    }
  }
}

interface SysRouteRouteChildren {
  SysRoleRoute: typeof SysRoleRoute
  SysUserRoute: typeof SysUserRoute
}

const SysRouteRouteChildren: SysRouteRouteChildren = {
  SysRoleRoute: SysRoleRoute,
  SysUserRoute: SysUserRoute,
}

const SysRouteRouteWithChildren = SysRouteRoute._addFileChildren(
  SysRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SysRouteRoute: SysRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
